name: NotRegionKills
version: '${project.version}'
main: me.jadenp.notregionkills.NotRegionKills
api-version: '1.20'
depend:
  - PlaceholderAPI
  - Worldguard
  - MythicMobs
soft-depend:
  - MythicMobs
