name: NotRegionKills
version: '${project.version}'
main: me.jadenp.notregionkills.NotRegionKills
description: Track region mob kills through a placeholder.
depend:
  - PlaceholderAPI
  - WorldGuard
soft-depend:
  - MythicMobs
